/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "X Values": "X 值",
    "You need to enable JavaScript to run this app.": "您需要启用 JavaScript 才能运行此应用程序。",
    "UNLOCK": "解锁",
    "Unlock": "解锁",
    "Shop": "商店",
    "to enable Basic Resets": "去启用基础重置",
    "Options": "选项",
    "My Formulas": "我的公式",
    "Formulas": "公式",
    "more formula": "更多公式",
    "First formula is free!!!": "第一个公式是免费的！！！",
    "Basic Formula": "基础公式",
    "EQUIPPED": "已装备",
    "GET": "获得",
    "Unequip": "卸下",
    "First Steps": "第一步",
    "Hint: Apply formulas repeatedly by holding the button or using the 1/2/3-Keys.": "提示：通过按住按钮或使用 1/2/3 键重复应用公式。",
    "New Milestone": "新里程碑",
    "[FULL INVENTORY]": "[插槽已满]",
    "-Reset": "-重置",
    "← Reset the shop for a new differential": "← 重置商店以获得新的微分",
    "A new differential of x and its formulas become available, but the shop is reset and the unlock cost for all non-basic formulas is 4 times as high.": "新的 x 微分及其公式可用，但商店已重置，所有非基本公式的解锁成本高出 4 倍。",
    "Accelerated": "加速",
    "Back To Zero": "归零",
    "Fill the Green Progress Bar": "填充绿色进度条",
    "Getting Jerky": "变得生涩",
    "Making Progress": "取得进展",
    "NO": "否",
    "Perform a Basic Reset": "执行基本重置",
    "Perform an x'-Reset": "执行 x'-重置",
    "Perform an x''-Reset": "执行 x''-重置",
    "Perform an x'''-Reset": "执行 x'''-重置",
    "Speedy": "快速",
    "YES": "是",
    "Basic Reset Pop-Up": "基础重置弹窗",
    "Decreasing Formula Pop-Up": "减少公式弹窗",
    "SCIENTIFIC": "科学",
    "This game is created by Zilvarro.": "游戏作者是：Zilvarro。",
    "Shop Scrollbar": "商店滚动条",
    "Shop Price Labels": "商店价格标签",
    "Offline Progress Pop-Up": "离线进度弹窗",
    "Number Format": "数字格式",
    "Pop-Up-Settings": "弹窗设置",
    "Manual Save": "手动保存",
    "Hard Reset": "硬重置",
    "Hotkey-Settings": "快捷键设置",
    "Must have 3 Milestones to join the Discord ☹": "必须有 3 个里程碑才能加入 Discord ☹",
    "Basic Reset": "基础重置",
    "← Reset x, but you can adapt your equipped formulas.": "← 重置 x，但你可以调整你装备的公式。",
    "Your X values are reset, but you can change your equipped formulas.": "您的 X 值已重置，但您可以更改装备的公式。",
    "for the next x-Reset": "以进行 下一个 x-重置",
    "Next Formula at x=": "下一个公式在 x=",
    "New Formula available": "新公式可用",
    "Game Saved": "游戏已保存",
    "Join the Discord Community": "加入 Discord 社区",
    "This resets everything and you do not get anything in return. Are you really sure?": "这会重置所有内容，您不会得到任何回报。 你真的确定吗？",
    "Are you really really sure?": "你真的确定吗？",
    "Are you totally absolutely enthusiastically sure?": "你完全绝对肯定吗？",
    "Game Reset": "游戏已重置",
    "increased by": "增加了 ",
    "Your": "你的",
    "You were away for": "你离开了",
    "CLOSE": "关闭",
    "Abort Alpha Pop-Up": "中止 阿尔法 弹出窗口",
    "Abort Hotkey [C]": "中止热键 [C]",
    "Advanced Display Modes": "高级显示模式",
    "Alpha": "阿尔法",
    "ALPHA": "阿尔法",
    "Alpha Upgrade Pop-Up": "阿尔法 升级弹出窗口",
    "Alpha-Reset Hotkey [A]": "阿尔法 重置热键 [A]",
    "Alpha-Reset Pop-Up": "阿尔法 重置弹出窗口",
    "Challenge Tab Switch": "挑战标签切换",
    "Exit Challenge Pop-Up": "退出挑战弹出窗口",
    "Header Display": "标题显示",
    "HORIZONTAL": "水平",
    "increased by a factor of": "增加了一个因素",
    "Mails": "邮件",
    "Memorize Pop-Up": "记住弹出窗口",
    "Save Imported": "保存导入",
    "Toggle Auto Hotkey [T]": "切换自动热键 [T]",
    "VERTICAL": "垂直",
    "x-Reset Pop-Up": "x-重置弹出窗口",
    "As a part of our Academy, you may now use our institutions for Research. You find Research on the Alpha tab. For Research it is important to not do your x-Resets immediately, but instead aim for a better highscore. The speed of your research is directly proportional to your highscores. If a highscore gets very much ahead of a Research level, you can even claim multiple levels at once! Research may not seem to help much when you first start, but its benefits grow exponentially, and they will soon speed up your daily work greatly.": "作为我们学院的一部分，您现在可以使用我们的机构进行研究。 您可以在 阿尔法 选项卡上找到 研究。 对于研究，重要的是不要立即进行 x 重置，而是要争取更高的高分。 您的研究速度与您的高分成正比。 如果高分远远超过研究级别，您甚至可以同时申请多个级别！ 刚开始的时候，研究似乎没什么帮助，但它的好处呈指数增长，很快就会大大加快你的日常工作。",
    "Due to your outstanding research in the field of x differentials and formulas, the Academy decided to support you on your journey as one of our members. You should already have received your very first Alpha Token. Your Alpha Tokens can be traded with us for various upgrades. You can obtain additional Alpha Tokens by getting the three differentials and then performing an Alpha Reset. If you manage to Alpha Reset with a very high x, we will award you with multiple Alpha Tokens at once!": "由于您在 x 微分和公式领域的杰出研究，学院决定支持您成为我们的成员之一。 您应该已经收到了您的第一个 阿尔法 代币。 您的 阿尔法 代币可以与我们交易以进行各种升级。 您可以通过获取三个差异然后执行 阿尔法 重置来获得额外的 阿尔法 代币。 如果您以非常高的 x 成功重置 阿尔法，我们将立即奖励您多个 阿尔法 代币！",
    "Hello again! x-Mail Prime includes unlimited access to: x-Books, our extensive e-Book library; x-Music, the only place where you can find the Idle Formulas Official Soundtrack; x-Games, our quadruple A gaming portal and x-Videos, our streaming service with only the best movies.": "再一次问好！ x-Mail Prime 包括无限制访问：x-Books，我们内容丰富的电子书库； x-Music，唯一可以找到 公式放置 官方配乐的地方； x-Games，我们的四重 A 游戏门户和 x-Videos，我们的流媒体服务，只提供最好的电影。",
    "Hi this is Henry again, thanks to you I learned that squaring a number is very powerful, the square increases really fast when the number increases. And it can even make negative numbers positive, how crazy is that? From now on I will use the square whenever I want to make big numbers!!!": "嗨，我还是 Henry，多亏了你，我才知道平方是非常强大的，当数字增加时，平方会增加得非常快。 而且它甚至可以让负数变成正数，这有多疯狂？ 从现在开始，每当我想做大数字时，我都会使用正方形！！！",
    "It is said there is a formula so powerful, that it can be used to alter the laws of reality. Some have dubbed it the \"Origin Formula\", others call it the \"God Formula\" but the name that resonates most with me is \"World Formula\". It seems that the World Formula is not something tangible: It's neither an object you can find, nor a formula you can just write down. Much rather, it appears to be a state of mind, some kind of enlightenment. A stream of conciousness that lets you unleash your full potential and ultimately allows you to go way beyond!": "据说有一个公式非常强大，可以用来改变现实的法则。 有人称它为“源方”，也有人称它为“神方”，但最让我产生共鸣的名字是“世界方”。 世界公式似乎不是有形的东西：它既不是你能找到的物体，也不是你可以写下来的公式。 更确切地说，它似乎是一种心态，某种启蒙。 一种意识流，让你释放你的全部潜能，并最终让你超越！",
    "I noticed how obsessed you were lately with researching formulas and large numbers, so I was sure you must have heard about it. About the mythical formula that is said to transcend maths itself. I've spent years following traces, not even sure why it is important or what my ultimate goal is. My curiousity led me deeper and deeper into the rabbit hole, but it was all in vain. Save yourself the trouble and stop digging deeper.": "我注意到你最近对研究公式和大数非常着迷，所以我相信你一定听说过。 关于据说超越数学本身的神话公式。 我花了数年时间追踪痕迹，甚至不确定它为什么重要或我的最终目标是什么。 好奇心让我越陷越深，但一切都是徒劳。 为自己省去麻烦，不要再深入挖掘了。",
    "So you've joined the Academy to aid your goals? They can be very helpful and you will need all help you can get. But be careful, you must not let them know you are looking for the world formula. We don't want the Academy to steal the fruits of our endeavors.": "所以你加入学院是为了帮助你实现目标？ 他们可能会非常有帮助，您将需要您所能获得的一切帮助。 但是要小心，千万不要让他们知道你在找世界公式。 我们不希望学院窃取我们努力的成果。",
    "Thank you for attempting the Formula God Challenge. That one is truly giving us nightmares. However, we are able to support you by multiplying your research speeds by your respective best scores in the Formula God Challenge. You can check this special boost on the Research tab. Keep trying and improving those highscores!": "感谢您尝试 公式上帝挑战。 那个真的让我们做噩梦。 但是，我们能够通过将您的研究速度乘以您在 公式上帝挑战 中各自的最佳成绩来为您提供支持。 您可以在“研究”选项卡上查看此特殊提升。 继续尝试并提高那些高分！",
    "We are very happy with the results of your Research so far. As such we would like to invite you to participate in more complex projects. Sometimes true wisdom can only be achieved by restricting ones options, forcing one to assume new perspectives. On the Alpha tab you can find our projects under Challenges. Every Challenge and Challenge segment you clear will allow us to make your formulas more efficient. And once you have proven yourself, there will be special rewards if you can help with the toughest Challenges our Academy faces right now.": "到目前为止，我们对您的研究结果感到非常满意。 因此，我们想邀请您参与更复杂的项目。 有时，真正的智慧只能通过限制一个人的选择，迫使一个人采取新的观点来实现。 在 阿尔法 选项卡上，您可以在挑战下找到我们的项目。 您清除的每个挑战和挑战部分都将使我们能够使您的公式更有效。 一旦你证明了自己，如果你能帮助我们学院目前面临的最严峻挑战，你将获得特别奖励。",
    "You are searching for it as well, aren't you? Please, stop before it is too late! The pursuit will rob you off your sleep, even once you know it is futile. For me it is too late to turn back, to give up. But I believe you can still be saved.": "你也在寻找它，是吗？ 请在为时已晚之前停下来！ 追求会夺走你的睡眠，即使你知道它是徒劳的。 对我来说，回头、放弃都为时已晚。 但我相信你还是可以得救的。",
    "Hi again, I hope you are doing well! Here's a small hint for you, since I have no idea where else to put it in the game: the result from applying a formula is generally rounded down (except for formulas that just add something to the current value). Maybe this will be helpful, or not, I don't know.": "再次问候，我希望你一切顺利！ 这是给你的一个小提示，因为我不知道在游戏中还能把它放在哪里：应用公式的结果通常会向下舍入（除了只是在当前值上加一些东西的公式）。 也许这会有所帮助，或者没有，我不知道。",
    "Hey, there are a lot of formulas in the shop now, and it's getting even more messy with each x-Reset. And many of the lower differential formulas seem pretty useless by now. But no worries, I have a solution: You can now highlight and filter your favorite formulas. Go, try it out!": "嘿，现在商店里有很多公式，而且每一次 x-重置 都变得更加混乱。 许多低微分公式现在看起来毫无用处。 但不用担心，我有一个解决方案：您现在可以突出显示和过滤您最喜欢的公式。 去，试试看！",
    "-Infinity": "-无穷",
    ", those negative numbers can become": ", 这些负数可以变成",
    ". Here are the exercises for you:": ". 以下是适合您的练习：",
    ". Yet one must not just invent new formulas, instead one must": ". 然而，我们不仅要发明新的公式，还必须",
    "\" Challenge?": "\“ 挑战？",
    "\"Master of Idle\" and \"Formula God\" give additional secret perks.": "“Master of Idle”和“Formula God”提供额外的秘密福利。",
    "(a.k.a. \"Why am I even doing these?\")": "（又名“我为什么要做这些？”）",
    "(Fully Idle)": "（完全放置）",
    "(Infinity)": "（无穷）",
    "/ 5 Stars": "/ 5 颗星",
    "/ 5 stars.": "/ 5 颗星。",
    "/4 Complete": "/4 完成",
    "~Bad Ending~": "~坏结局~",
    "5 - Infinity": "5 - 无限",
    "A new Era": "一个新时代",
    "Abort": "中止",
    "About Challenges": "关于挑战",
    "About the Academy": "关于学院",
    "Academy": "学院",
    "Academy Projects": "学院项目",
    "All challenges have a 30 minute time limit.": "所有挑战都有 30 分钟的时间限制。",
    "All previous challenges at once.": "一次完成所有先前的挑战。",
    "All X-Values decay at a rate of 10% per second, rounded up.": "所有 X 值都以每秒 10% 的速度衰减，四舍五入。",
    "Alpha Millionnaire": "阿尔法百万富翁",
    "Alpha Reset for": "阿尔法重置为",
    "Alpha Resetter": "阿尔法重置器",
    "Alpha Token": "阿尔法代币",
    "Alpha Upgrades": "阿尔法升级",
    "ALREADY BOUGHT!": "已经购买！",
    "Applies a formula for you twice per second, if beneficial. Rate can be further upgraded.": "如果有益，每秒为您应用两次公式。 房价可以进一步提升。",
    "Applying a formula resets all other X-Values.": "应用公式会重置所有其他 X 值。",
    "Applying formulas does not reduce x.": "应用公式不会减少 x。",
    "Auto": "自动",
    "Auto Applier (free)": "自动涂抹器（免费）",
    "Auto Applier can handle multiple formulas simultaneously.": "Auto Applier 可以同时处理多个配方。",
    "Auto Applier works offline.": "Auto Applier 离线工作。",
    "Auto Rememberer": "自动记忆",
    "Auto Research": "自动研究",
    "Auto Unlocker": "自动解锁器",
    "Automatically performs Alpha-Resets. Can also complete Challenges.": "自动执行阿尔法重置。 也可以完成挑战。",
    "Automatically performs x-Resets.": "自动执行 x 重置。",
    "Automatically starts researches.": "自动开始研究。",
    "Automatically unlocks formulas. Unlocking formulas does not reduce x.": "自动解锁公式。 解锁公式不会减少 x。",
    "Average rating:": "平均评分：",
    "Base α-Reset Tokens:": "基础 α-重置代币：",
    "Basic Resets are disabled.": "基本重置被禁用。",
    "Be careful!": "当心！",
    "Best Fully Idle:": "最佳完全放置：",
    "Better Memory": "更好的记忆力",
    "Bonus:": "奖励：",
    "Boost:": "促进：",
    "Breaking Maths": "打破数学",
    "Brilliant Scientist": "天才科学家",
    "But how???": "但是怎么办？？？",
    "Buy 9 Alpha Upgrades": "购买 9 个 阿尔法 升级",
    "Bye": "再见",
    "Challenge Accepted": "已接受的挑战",
    "Challenger": "挑战者",
    "Challenges": "挑战",
    "Challenges are like normal Alpha-Runs, but with additional constraints.": "挑战就像正常的 阿尔法-运行，但有额外的限制。",
    "Challenges are NOT ordered by difficulty.": "挑战不按难度排序。",
    "Clear a Challenge": "清除挑战",
    "Complexity": "复杂",
    "Congratulations on finishing the Master of Idle Challenge. We improved your Passive Alpha gain, from now on you will get Alpha based on your best fully idle Alpha run. You can check it on the Alpha upgrades tab.": "恭喜你完成了 Master of Idle Challenge。 我们改进了您的被动 阿尔法 增益，从现在开始，您将根据您最好的完全闲置 阿尔法 运行获得 阿尔法。 您可以在 阿尔法 升级选项卡上查看它。",
    "Countdown": "倒数",
    "Deal!": "交易！",
    "Decay": "衰变",
    "Decrement": "递减",
    "Deepest Desire": "最深的渴望",
    "DEFAULT": "默认",
    "Description": "描述",
    "Dev": "开发",
    "discover": "发现",
    "Display Mode": "显示模式",
    "during Formula God": "公式神期间",
    "Each completed segment grants +15% Formula Efficiency.": "每个完成的部分都会提供 +15% 的公式效率。",
    "Each formula can only be used one time per reset.": "每个公式每次重置只能使用一次。",
    "EDIT": "编辑",
    "Endings": "结局",
    "Every fully completed challenge doubles your Formula Efficiency.": "每个完全完成的挑战都会使您的公式效率加倍。",
    "Every maxxed Research Bar doubles your Formula Efficiency (x": "每个最大化的研究栏都会使您的公式效率加倍（x",
    "Exactly, the teacher learns more than the student! That's why you are going to pay me some Alpha Tokens for the privilege of helping my boys!": "没错，老师比学生学得更多！ 这就是为什么你要付给我一些 阿尔法 代币，以获得帮助我的孩子们的特权！",
    "Exit Challenge": "退出挑战",
    "exploit the core of mathematics": "利用数学的核心",
    "Fastest Alpha run:": "最快的阿尔法运行：",
    "FAVORITES": "最爱",
    "find that powerful formula": "找到那个强大的公式",
    "Flawless! You sent back the correct answers with explanations.": "完美无瑕！ 你发回了正确的答案和解释。",
    "Formula God": "公式神",
    "Formula Offline Progress is disabled during Challenges.": "公式离线进度在挑战期间被禁用。",
    "Formula Refund": "公式退款",
    "Formula Slot": "公式插槽",
    "Formulas from previous x-Resets are no longer available.": "以前的 x-Resets 中的公式不再可用。",
    "Gain Alpha Tokens passively in Intervals of the fastest Alpha-Reset (min 1/day). Works offline!": "在最快的 阿尔法 重置间隔内被动获得 阿尔法 代币（最少 1 次/天）。 离线工作！",
    "Gary": "加里",
    "Gary's Homework": "加里的作业",
    "Get a Research to Level 2500": "研究达到 2500 级",
    "go towards Infinity": "走向无限",
    "Googol": "古戈尔",
    "Grants an additional formula equipment slot.": "授予一个额外的公式设备插槽。",
    "Hearing about the world formula, you may be wondering how to achieve such a state of mind, how to": "听到世界公式，你可能想知道如何达到这样的心态，如何",
    "Hello, I am rich prince. Inheritance is good! I can make x very big. But need money for that. Give me. You be make happy then!": "大家好，我是富贵公子。 传承不错！ 我可以使 x 非常大。 但是为此需要钱。 给我吗。 那时你会很开心！",
    "Hello! Thank you for using x-Mail as your eMail client. To get the most out of your experience with x-Mail, upgrade now to an x-Mail Prime Membership!": "你好！ 感谢您使用 x-Mail 作为您的电子邮件客户端。 要充分利用您的 x-Mail 体验，请立即升级为 x-Mail Prime 会员！",
    "Help with Homework": "帮助家庭作业",
    "Henry": "亨利",
    "Henry's Homework": "亨利的作业",
    "Here are the latest results of the survey:": "以下是调查的最新结果：",
    "Hey, you are good with numbers aren't you? Can you help my sons with his maths homework?": "嘿，你很擅长数字，不是吗？ 你能帮我儿子做数学作业吗？",
    "Hi I'm Gary, the oldest brother. My homework is about infinities or something. Here are the exercises for you:": "大家好，我是大哥 Gary。 我的作业是关于无穷大之类的。 以下是适合您的练习：",
    "Hi I'm Henry, Klausi's older brother. My homework is about squares and negative numbers. The teacher said the insights from the bold questions could become very important for": "大家好，我是 Henry，Klausi 的哥哥。 我的作业是关于平方和负数的。 老师说从大胆的问题中得到的见解可能会变得非常重要",
    "Hi I'm Jimmy, Tommy's older stepbrother. My homework is about square roots and cubic roots or something. Here are the exercises for you:": "大家好，我是吉米，是汤米的继兄。 我的作业是关于平方根和立方根之类的。 以下是适合您的练习：",
    "Hi I'm Klausi. My homework is about eights and zeroes or something. Here are the exercises for you:": "嗨，我是克劳西。 我的家庭作业是关于八和零之类的。 以下是适合您的练习：",
    "Hi I'm Tommy, Henry's older brother. My homework is about logarithms or something. Here are the exercises for you:": "大家好，我是汤米，亨利的哥哥。 我的作业是关于对数什么的。 以下是适合您的练习：",
    "Hi this is Karen again. My sons got top scores on the test thanks to your help. I was a little harsh with you and wanted to apologize for that. Thank you so much for teaching my kids!": "大家好，我又是卡伦。 由于您的帮助，我的儿子们在考试中取得了最高分。 我对你有点苛刻，想为此道歉。 非常感谢您教我的孩子们！",
    "Hi, I hope you are enjoying this game! Please take a moment and rate your experience on a scale of 1 to 5 stars.": "嗨，我希望你喜欢这个游戏！ 请花点时间按照 1 到 5 星的等级给您的体验打分。",
    "Highlight your favorite formulas!": "突出显示您最喜欢的公式！",
    "Homework is done": "作业完成",
    "How can I give you?": "我怎么给你",
    "I am very happy with that!": "我很高兴！",
    "I heard you found a rare stone? I do not know what it is and what to do with it. But you can find your stones on the Alpha tab. Feel free to experiment with them, though I am not sure if they will turn out to be useful for anything.": "听说你找到了稀有的石头？ 我不知道它是什么以及如何处理它。 但是您可以在 阿尔法 选项卡上找到您的宝石。 随意试验它们，尽管我不确定它们是否对任何事情都有用。",
    "I knew that before!": "我以前就知道！",
    "I love Squaring now": "我现在喜欢平方",
    "I love Upgrades": "我爱升级",
    "I see you are still working on those formulas, despite my warnings. Maybe I'll share some of my most recent findings with you...": "我看到你仍然在研究那些公式，尽管我已经发出警告。 也许我会和你分享我最近的一些发现……",
    "I think I'll pass": "我想我会通过",
    "I will get back to you with the survey results in a day or two.": "我会在一两天内将调查结果回复给您。",
    "if you put in bigger and bigger numbers. Seems like a lot to me.": "如果你输入越来越大的数字。 对我来说似乎很多。",
    "Increment": "增量",
    "Infinity": "无穷",
    "Infinity - Infinity": "无限 - 无限",
    "Infinity + Infinity": "无限+无限",
    "Info": "信息",
    "Jimmy": "吉米",
    "Jimmy's Homework": "吉米的家庭作业",
    "Join the Academy and buy an Alpha Upgrade": "加入学院并购买 阿尔法 升级",
    "Just a small hint": "只是一个小提示",
    "Karen": "凯伦",
    "Klausi": "克劳西",
    "Klausi's Homework": "克劳西的作业",
    "Level 100 for every Research": "每项研究达到 100 级",
    "Level:": "等级：",
    "Limited": "有限的",
    "logarithms of fractions can produce negative results": "分数的对数会产生负结果",
    "makes things bigger, and that square roots and logarithms": "让事情变大，然后平方根和对数",
    "Master of Idle": "放置大师",
    "MAXXED": "MAXXED",
    "Maxxed Research": "最大研究",
    "Memorize": "背诵",
    "Memorize Equip": "记忆装备",
    "Memorized equipment is automatically loaded when differentials are unlocked.": "当差速器解锁时，记忆的设备会自动加载。",
    "MINIMUM": "最低限度",
    "Mister Y": "Y先生",
    "multiplies your Starting x": "乘以你的起始 x",
    "My Findings": "我的发现",
    "No limit": "没有限制",
    "Not defined": "没有定义的",
    "Now prince can feed family. We poor. You have big heart. Attachment will double your x! But can only use once!": "现在王子可以养家糊口了。 我们穷。 你有大心脏。 附件将使您的x倍增！ 但是只能使用一次！",
    "Offline Applier": "离线应用程序",
    "on x'-Reset": "在 x'-复位",
    "on x''-Reset": "在 x''-复位",
    "on x'''-Reset": "在 x'''-重置",
    "on α-Reset": "在 α-复位",
    "One Equipment loadout can be saved and loaded for each stage.": "可以为每个阶段保存和加载一个设备装载。",
    "One-Shot": "一次性",
    "Only simple formulas are available.": "只有简单的公式可用。",
    "Open Attachment: xdoubler.exe": "打开附件：xdoubler.exe",
    "or whatever you were looking for!": "或者你正在寻找的任何东西！",
    "Passive Alpha": "被动阿尔法",
    "Passive Alpha Tokens:": "被动阿尔法代币：",
    "positive by squaring": "平方为正",
    "Prince": "王子",
    "Production is 100x slower.": "生产速度慢了 100 倍。",
    "Rating submitted": "评分已提交",
    "Re: How can I give you?": "Re: 我怎么给你？",
    "Re: Sure, maybe I can learn a thing too!": "回复：当然，也许我也能学到东西！",
    "Re: What are you talking about?": "回复：你在说什么？",
    "Remember": "记住",
    "Rememberer": "记忆者",
    "Research": "研究",
    "Research speed is boosted by your highscores but higher levels take longer.": "您的高分会提高研究速度，但更高的水平需要更长的时间。",
    "Researcher": "研究员",
    "Reset": "重置",
    "Selfish": "自私",
    "Simple formulas are not available, except for Basic formulas.": "简单公式不可用，基本公式除外。",
    "Simplicity": "简单",
    "Single Use": "单人使用",
    "Slowness": "缓慢",
    "Small Backpack": "小背包",
    "So how exactly did I profit?": "那么我究竟是如何获利的呢？",
    "something": "某物",
    "Special:": "特别的：",
    "sqrt(Infinity)": "开方（无穷大）",
    "Start the \"": "启动\"",
    "Start with x=6.36e12 after resets": "重置后从 x=6.36e12 开始",
    "Starting Stones": "起始石",
    "State your greatest wish": "说出你最大的愿望",
    "Still here?": "还在？",
    "Stone Skipper": "石头跳跃者",
    "Stones": "石头",
    "subtracting negative numbers": "减去负数",
    "Super Applier": "超级应用程序",
    "Sure, maybe I can learn a thing too!": "当然，也许我也能学到东西！",
    "Survey": "民意调查",
    "Survey Results": "调查结果",
    "Target": "目标",
    "Thank you": "谢谢",
    "Thank you for your participation.": "感谢您的参与。",
    "Thank you so much": "太感谢了",
    "Thanks for your Interest!": "感谢您的关注！",
    "That's all their homework done. Let's see how my boys do in the upcoming tests. Or if": "这就是他们完成的所有作业。 让我们看看我的孩子们在即将到来的测试中表现如何。 或者如果",
    "The Academy committee is very impressed with your Research. For every field of research that you fully complete, we will double your Formula Efficiency. Keep up the good work!": "学院委员会对您的研究印象深刻。 对于您完全完成的每个研究领域，我们将使您的配方效率翻倍。 保持良好的工作！",
    "The World Formula can be very dangerous in the wrong hands! It can manifest all sorts of energies. If you ever happen to find it, I trust that you will make the right choice.": "世界公式落入坏人之手非常危险！ 它可以表现出各种能量。 如果您碰巧找到它，我相信您会做出正确的选择。",
    "the World Formula for yourself. One must break out of the prison imposed by ones formulas. Find unlimited growth. Yearn for": "自己的世界方程式。 一个人必须打破那些公式强加的监狱。 寻找无限的成长。 渴望着",
    "them,": "他们，",
    "Time in current Alpha run:": "当前 阿尔法 运行时间：",
    "Timed Out": "时间到",
    "Timewall": "时间墙",
    "to break free of the bounds which constrain ones conciousness. And those who get blinded by greed and stop being careful may end up stuck with infinitely many problems, or deep down in the depths of hell.": "打破束缚一个人意识的界限。 而那些被贪婪蒙蔽而不再谨慎的人，最终可能会陷入无穷无尽的问题，或者陷入地狱的深处。",
    "Tommy": "汤米",
    "Tommy's Homework": "汤米的家庭作业",
    "Total submissions: 28": "提交总数：28",
    "Transfer money. $150! Have only one day. But must not be suspicious. Must transfer only one dollar at a time!": "划款。 150 美元！ 只有一天。 但切不可起疑。 一次只能转一美元！",
    "Transferred": "转入",
    "Transferred enough": "调够了",
    "Trendsetter": "潮流引领者",
    "Ultimate Scientist": "终极科学家",
    "UNLOCK CHALLENGES": "解锁挑战",
    "UNLOCK RESEARCH": "解锁研究",
    "UNLOCK SHOP DISPLAY MODE": "解锁商店展示模式",
    "UNLOCK STARTING STONES": "解锁起始石",
    "Up to three different Equipment loadouts can be saved.": "最多可以保存三个不同的设备装载。",
    "Upgrade Complete": "升级完成",
    "Upgrades": "升级",
    "Warning": "警告",
    "Welcome to the Academy": "欢迎来到学院",
    "Well now you know that": "那么现在你知道了",
    "were the only one to profit from this.": "是唯一从中获利的人。",
    "What are you talking about?": "你在说什么？",
    "What's included in the membership?": "会员资格包括什么？",
    "World Formula": "世界方程式",
    "X Resetter": "X复位器",
    "x-Mail": "邮箱",
    "x-Mail Prime": "x-mail Prime",
    "x-Mail Prime Advantages": "x-Mail Prime 优势",
    "Yeah, good for you. Now stop annoying me and my children for your stupid research. Stop wasting our time and instead go": "是的，对你有好处。 现在别再因为你的愚蠢研究而烦扰我和我的孩子们了。 不要浪费我们的时间，而是去",
    "Yeah, I'd rather not get involved in this.": "是的，我宁愿不参与其中。",
    "Yes, please!": "是的，请！",
    "you": "你",
    "You are rewarded for each successful x-Reset and for completing the entire run!": "每次成功的 x-Reset 和完成整个运行都会奖励您！",
    "You can do at most 100 formula applications per x-Reset.": "每个 x-Reset 最多可以进行 100 次公式应用。",
    "You cannot interact with anything on the Formulas tab.": "您无法与“公式”选项卡上的任何内容进行交互。",
    "You completed all challenges, boosting your Formula Efficiency by": "您完成了所有挑战，通过以下方式提高了公式效率",
    "You must do a reset every 30 seconds.": "您必须每 30 秒重置一次。",
    "You only have 1 equipment slot, but the first formula apply after a reset is free.": "您只有一个装备槽，但重置后应用的第一个公式是免费的。",
    "You will lose your current formula progress.": "您将失去当前的公式进度。",
    "Your feedback has been submitted!": "您的反馈已提交！",
    "Your Prince": "你的王子",
    "Your Profit": "您的利润",
    "Your rating:": "你的评分：",
    "Your submission has been received. Thank you for your feedback. If you are interested, I can inform you about the results of the survey.": "您的提交已收到。 感谢您的反馈意见。 如果你有兴趣，我可以告诉你调查的结果。",
    "Your total Starting x is": "您的总起始 x 是",
    "α in": "α在",
    "α-Reset": "α-重置",
    "α-Reset while having at least four billion Alpha and x=1e110": "α-重置，同时至少有 40 亿 阿尔法 和 x=1e110",
    "α-Reset with x=1e100 or more": "α-重置 于 x=1e100 或更多",
    "a million Alpha": "百万阿尔法",
    "Buy everything on the Alpha Upgrades Tab": "在 阿尔法 升级选项卡上购买所有东西",
    "Complete all Challenges": "完成全部挑战",
    "exactly s": "恰好是",
    "Find the World Formula": "寻找世界公式",
    "Get all Research Bars to Level 2500": "将所有研究条升至 2500 级",
    "three distinct Bad Endings": "三个截然不同的坏结局",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "s": "",
    "for": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Need: ": "需要：",
    "Reach ": "达到 ",
    "Apply Formula Hotkeys ": "应用公式热键 ",
    "Basic Reset Hotkey ": "基础重置快捷键 ",
    "Version:": "版本：",
    "Playtime:": "游戏时长：",
    "x-Reset Hotkey ": "x-重置快捷键",
    "Cost:": "成本：",
    "Loadout ": "装载 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Click to apply!": "点击以允许！",
    "Need: x=": "需要: x=",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)m([\d\.]+)s$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^ ([\d\.,]+)$/,
    /^  ([\d\.,]+)$/,
    /^   ([\d\.,]+)$/,
    /^    ([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^x\=([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x\=([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^x\'\'\' produces (.+) times as fast$/, 'x\'\'\' 产生 $1 次那么快'],
    [/^x\'\' produces (.+) times as fast$/, 'x\'\' 产生 $1 次那么快'],
    [/^x\' produces (.+) times as fast$/, 'x\' 产生 $1 次那么快'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d([\d\.]+)h([\d\.]+)m([\d\.]+)s$/, '$1天 $2小时 $3分 $4秒'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);